webtalk_init -webtalk_dir D:/GroupProject/WindTunnelApparatus/Firmware/FPGA/FPGATests/I2CTest/I2CTest.sim/sim_1/behav/xsim.dir/topmodule_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 27 21:06:38 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210799755_0_0_666" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "de4bc1c903d0511c94a0b8e66df50a1a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a83a143ac694f22b64acd585bc65675" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "501 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "26772_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1428388312 -regid "210799755_0_0_666" -xml D:/GroupProject/WindTunnelApparatus/Firmware/FPGA/FPGATests/I2CTest/I2CTest.sim/sim_1/behav/xsim.dir/topmodule_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/GroupProject/WindTunnelApparatus/Firmware/FPGA/FPGATests/I2CTest/I2CTest.sim/sim_1/behav/xsim.dir/topmodule_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/GroupProject/WindTunnelApparatus/Firmware/FPGA/FPGATests/I2CTest/I2CTest.sim/sim_1/behav/xsim.dir/topmodule_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
